const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const TOGGLE_COMPLETED = "TOGGLE_COMPLETED";
const TOGGLE_ALL_COMPLETED = "TOGGLE_ALL_COMPLETED";
const EDIT_CONTENT = "EDIT_CONTENT";

export {
  ADD_TODO,
  DELETE_TODO,
  TOGGLE_COMPLETED,
  EDIT_CONTENT,
  TOGGLE_ALL_COMPLETED,
};
